# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='UProfile',
        ),
    ]
