# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_auth', '0003_auto_20171013_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about_me_en',
            field=models.TextField(blank=True, null=True, verbose_name='About me'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='about_me_uk',
            field=models.TextField(blank=True, null=True, verbose_name='About me'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Avatar'),
        ),
    ]
