# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20171017_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='read_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
