# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20171025_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=80, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=80, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_uk',
            field=models.CharField(max_length=80, null=True, verbose_name='Title'),
        ),
    ]
